#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_MAIN                                100
#define IDD_ABOUT                               101
#define IDD_SETTINGS                            102
#define IDR_PrefsFileMask                       104
#define IDD_THINKING                            105
#define IDD_ADD_FILE_MASK                       106
#define IDR_MAIN_FILE_LIST                      109
#define IDD_EXIF_Browser                        111
#define IDC_MAIN_ADD_FOLDER                     20004
#define IDC_MAIN_ADD_PICTURE                    20008
#define IDC_MAIN_DELETE                         20016
#define IDC_MAIN_ERASE                          20020
#define IDC_MAIN_FILE_LIST                      20024
#define IDC_MAIN_INFO                           20028
#define IDC_MAIN_PATTERN                        20032
#define IDC_MAIN_RENAME                         20036
#define IDC_MAIN_SAVE                           20038
#define IDC_MAIN_SETTINGS                       20040
#define IDC_MAIN_SYNC                           20044
#define IDC_PREFS_APPLY                         21002
#define IDC_PREFS_CANCEL                        21004
#define IDC_PREFS_DATE_SHOOT_PRIMARY            21008
#define IDC_PREFS_DATE_SHOOT_SECONDARY          21016
#define IDC_PREFS_FILE_MASK                     21018
#define IDC_PREFS_NX_STUDIO                     21020
#define IDC_PREFS_ON_CONFLICT                   21022
#define IDC_PREFS_ON_CONFLICT_ADD               21024
#define IDC_PREFS_ON_CONFLICT_NUM               21026
#define IDC_PREFS_RESET_SETTING                 21028
#define IDC_PREFS_SAVE_SETTING                  21030
#define IDC_PREFS_DRAG_N_DROP                   21032
#define IDC_PREFSAddAMask                       21040
#define IDC_PREFSDelPattern                     21042
#define IDC_PREFSExifToolBrowse                 21048
#define IDC_PREFS_EXIF_Engine                   21050
#define IDC_PREFS_ExifToolPath                  21052
#define IDC_ABOUT_BUILDDATE                     22002
#define IDC_ABOUT_TITLE                         22004
#define IDC_ABOUT_VERSION                       22006
#define IDM_PrefsFileMaskAdd                    24000
#define IDC_AddPatDescription                   24002
#define IDC_AddFileMaskFileMask                 24003
#define IDC_PROGRESS                            25001
#define IDB_SETTINGS                            32158
#define IDC_ABOUT_DESCRIPTION                   40000
#define IDC_EXIF_Browse_Cancel                  40000
#define IDC_THINKING_Cancel                     40000
#define IDM_ADD_PICTURE                         40000
#define IDC_COPYRIGHT                           40001
#define IDC_EXIF_BROWSER_List                   40001
#define IDM_ADD_FOLDER_OF_PICTURES              40001
#define IDM_PrefsFileMaskDel                    40001
#define IDC_ABOUT_ST_AUTHOR                     40002
#define IDM_REMOVE_FROM_LIST                    40002
#define IDC_ABOUT_ST_COPY                       40003
#define IDM_CLEAR_LIST                          40003
#define IDC_AUTHOR                              40004
#define IDM_MANUALLY_RENAME                     40004
#define IDC_ABOUT_BUILT                         40005
#define IDM_LOCK                                40005
#define IDM_EXIF_BROWSER                        40006
#define IDC_ABOUT_ST_VER                        40007
#define IDI_PROG_ICON                           41019
#define IDC_MASK                                41022
